#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar 24 11:19:54 2022

@author: don
"""

v = - 99999

for i in range(len(T)):
    if T[i] > v:
        imax = i
        v = T[i]
        
    return v, imax 

# -----------------------------------

v = None

for i in range(len(T)):
    if v is None or T[i] > v:
        imax = i
        v = T[i]
        
    return v, imax 


# -----------------------------------

